export class GlobalConstants {
    public static ANGLES = ['modXHorizontal',
                            'modXVertical',
                            'modXDiagonalX',
                            'modXDiagonalY',
                            'modXDiagonalCDownX',
                            'modXDiagonalCDownY',
                            'modXDiagonalCLeftX',
                            'modXDiagonalCLeftY',
                            'modXDiagonalCUpX',
                            'modXDiagonalCUpY',
                            'modXDiagonalCRightX',
                            'modXDiagonalCRightY',
                            'modYHorizontal',
                            'modYVertical',
                            'modYDiagonalX',
                            'modYDiagonalY',
                            'modYDiagonalCDownX',
                            'modYDiagonalCDownY',
                            'modYDiagonalCLeftX',
                            'modYDiagonalCLeftY',
                            'modYDiagonalCUpX',
                            'modYDiagonalCUpY',
                            'modYDiagonalCRightX',
                            'modYDiagonalCRightY',
                            'lHorizontal',
                            'lVertical',
                            'lUpDiagonalX',
                            'lUpDiagonalY',
                            'lDownDiagonalX',
                            'lDownDiagonalY',
                            'rHorizontal',
                            'rVertical',
                            'rUpDiagonalX',
                            'rUpDiagonalY',
                            'rDownDiagonalX',
                            'rDownDiagonalY'];

    public static PINS = ['gamecubeConsole',
                            'A',
                            'B',
                            'X',
                            'Y',
                            'Z',
                            'L',
                            'R',
                            'START',
                            'UP',
                            'LEFT',
                            'DOWN',
                            'RIGHT',
                            'MODX',
                            'MODY',
                            'CUP',
                            'CLEFT',
                            'CDOWN',
                            'CRIGHT'];

    public static DISCORD_URL = 'https://discord.gg/6wcEaDU';
    public static GITHUB_URL = 'https://github.com/Crane1195/DIYB0XX';
}
